### PR TITLE
add map, apply, alternative versions of operators

### PR DESCRIPTION
**Pull request by 7sharp9**

### CODE REVIEW

**Comment by wallymathieu** [comment]
Looks good, I guess the intent here is to present these as module functions for ConcreteCodec?

**Comment by gusty** [comment]
To me the argument order is a bit unexpected.
I'll be in favor of renaming them, for instance `map` with arguments flipped is called `for` in Haskell, though here it's a reserved word.

**Comment by wallymathieu** [comment]
I didn't notice the argument order. Could it be that the argument order was unintentional? @7sharp9

**Comment by gusty** [comment]
No, it was intentional in order to be able to construct idioms for applicatives/alternatives using forward pipe instead of other operators.

He needed for Falanx, but apparently he solved the operator restriction already.

**Comment by wallymathieu** [comment]
Should this PR be closed? @7sharp9

**Comment by gusty** [comment]
Yes

**Pull request closed without merging**
